package exam.exception;

public class error2 {

    public static void main(String[] args) {
    //     try{
    //         int []a= new int[4];
    //         a[4]=10;
    //     }
    //     catch(ArrayIndexOutOfBoundsException e){
    //      System.out.println("exception name is :"+e);
    //     }
    //     System.out.println("adnan rony");
        
    // }
//     try
//                 {
//                 System.out.printf("1");
//                 int sum = 9 / 0;
//                 System.out.printf("2");
//                 }
//                 catch(ArithmeticException e)
//                 {
//                 System.out.printf("3");
//                 }
//                 catch(Exception e) 
//                 {
//                 System.out.printf("4");
//                 }
//                 finally
//                 {
//                 System.out.printf("5");
//                 }
//                 }

// }
    }